<!-- B032 -->
    <li><a href="/cgi-bin/koha/stack/stack-retrieval.pl">Retrieval</a></li>
    <li><a href="/cgi-bin/koha/stack/stack-delivery.pl">Delivery</a></li>
    <li>
        <span>All operations:</span>
        <form action="/cgi-bin/koha/stack/all-operations.pl" method="get">
            <input type="text" name="input" size="10" class="focus" />
            <input type="submit" class="submit" value="OK" />
        </form>
    </li>
    
    <li style="margin-top: .5em">
        <a href="/cgi-bin/koha/stack/search-stacks.pl">Stack requests list</a>
    </li>
    <li><a href="/cgi-bin/koha/stack/search-items-temp.pl">Temporary items list</a></li>
    
    <li style="margin-top: .5em">
        <a href="/cgi-bin/koha/stack/stack-request.pl">Stack requests from card catalog</a>
    </li>
<!-- END B032 -->
