<!-- PROGILONE - april 2010 - F21 -->
<!-- TMPL_IF NAME="OPACBranchTooltipDisplay" -->
<span class="branchdetails" ><!-- TMPL_IF NAME="branchaddress1" --><span class="branchaddress" ><!-- TMPL_VAR NAME="branchaddress1" --></span><!-- /TMPL_IF -->
    <!-- TMPL_IF NAME="branchaddress2" --><span class="branchaddress" ><!-- TMPL_VAR NAME="branchaddress2" --></span><!-- /TMPL_IF -->
    <!-- TMPL_IF NAME="branchaddress3" --><span class="branchaddress" ><!-- TMPL_VAR NAME="branchaddress3" --></span><!-- /TMPL_IF -->
    <!-- TMPL_IF NAME="branchcity" --><span class="branchaddress" ><!-- TMPL_VAR NAME="branchzip" --> <!-- TMPL_VAR NAME="branchcity" --></span><!-- /TMPL_IF -->
    <!-- TMPL_IF NAME="branchcountry" --><span class="branchaddress" ><!-- TMPL_VAR NAME="branchcountry" --></span><!-- /TMPL_IF -->
    <!-- TMPL_IF NAME="branchphone" --><span class="branchphone" ><!-- TMPL_VAR NAME="branchphone" --></span><!-- /TMPL_IF -->
    <!-- TMPL_IF NAME="branchnotes" --><span class="branchnotes" ><!-- TMPL_VAR NAME="branchnotes" --></span><!-- /TMPL_IF -->
</span>
<!-- /TMPL_IF -->
<!-- End PROGILONE -->
