<h5>Guided Reports</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/guided_reports.pl">Guided Reports</a></li>
	</ul>

<h5>Statistics wizards</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/acquisitions_stats.pl">Acquisitions</a></li>
		<li><a href="/cgi-bin/koha/reports/borrowers_stats.pl">Patrons</a></li>
		<li><a href="/cgi-bin/koha/reports/catalogue_stats.pl">Catalog</a></li>
		<li><a href="/cgi-bin/koha/reports/issues_stats.pl">Circulation</a></li>
                <li><a href="/cgi-bin/koha/reports/serials_stats.pl">Serials</a></li>
	</ul>


	<h5>Top Lists</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/bor_issues_top.pl">Patrons with the most checkouts</a></li>
		<li><a href="/cgi-bin/koha/reports/cat_issues_top.pl">Most-Circulated Items</a></li>
	</ul>
	
	<h5>Inactive</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/borrowers_out.pl">Patrons who haven't checked out</a></li>
		<li><a href="/cgi-bin/koha/reports/catalogue_out.pl">Items with no checkouts</a></li>
	</ul>


	<h5>Other</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/itemslost.pl">Lost Items</a></li>
		<li><a href="/cgi-bin/koha/reports/manager.pl?report_name=itemtypes">Catalog by Item Type</a></li>
		<li><a href="/cgi-bin/koha/reports/issues_avg_stats.pl">Average loan time</a></li>
	</ul>
	
	<!-- B11 -->
	<h5>Jasper</h2>
	<ul>
		<li><a href="/cgi-bin/koha/edition/circulation.pl">Circulation statistics</a></li>
		<li><a href="/cgi-bin/koha/edition/recolement.pl">Recolement statistics</a></li>
		<li><a href="/cgi-bin/koha/edition/expiredreserves.pl">Expired reserves</a></li>
		<li><a href="/cgi-bin/koha/edition/expiredcommunications.pl">Expired stack requests</a></li>
		<li><a href="/cgi-bin/koha/edition/nonreturnedstacks.pl">Non returned stack requests</a></li>
		<li><a href="/cgi-bin/koha/edition/completedspacebookingofday.pl">Completed Spaces bookings of day which have to be clean</a></li>
	</ul>
	<!-- END B11 -->
